
select ?concept ?type ?label where
{ graph <http://data.europa.eu/esco/semic>
   {
      ?concept <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type .
      ?concept <http://www.tenforce.com/esco/java#fallbackLabel> ?label .
   }
}